import React, { useEffect, useRef, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import SonicLogoItem from "../SonicLogoItem/SonicLogoItem";
import "./SonicLogoPanel.css";
import { filter } from "lodash";
import useSonicLogoTrackPlayPause from "../../../../customHooks/useSonicLogoTrackPlayPause";
import showNotification from "../../../../common/helperFunctions/showNotification";
import { SET_SONIC_LOGO_TRACK_META } from "../../redux/sonicLogoTrackSlice";
import { SET_AI_MUSIC_META } from "../../redux/AIMusicSlice";
import axiosSSPrivateInstance from "../../../../axios/axiosSSPrivateInstance";
import ModalWrapper from "../../../../branding/componentWrapper/ModalWrapper";
import AppendSonicLogo from "../../../../common/components/AppendSonicLogo/AppendSonicLogo";

const getAllSonicLogoTracks = async () => {
  const allSonicTracks = await axiosSSPrivateInstance.get(
    `/tuneytracksoniclogo/getAllSonicLogoTracks`
  );
  return allSonicTracks?.data;
  // return [
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "A#min",
  //     mp3FileName: "Vodafone_Soniclogo_FaA0vo_2025-07-31T130745.mp3",
  //     matchingKeyId: "17",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "A#m",
  //     keyId: "17",
  //     id: 53,
  //     title: "Electronic",
  //     matchingKeyTuneyName: "A#m",
  //     userId: 588,
  //     keyDisplayName: "A#min",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "A#min",
  //     mp3FileName: "Vodafone_Soniclogo_jqf0Qn_2025-07-31T132403.mp3",
  //     matchingKeyId: "17",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "A#m",
  //     keyId: "17",
  //     id: 77,
  //     matchingKeyTuneyName: "A#m",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "A#min",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "A#min",
  //     mp3FileName: "Vodafone_Soniclogo_X5hFk0_2025-07-31T124042.mp3",
  //     matchingKeyId: "17",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "A#m",
  //     keyId: "17",
  //     id: 131,
  //     title: "Main",
  //     matchingKeyTuneyName: "A#m",
  //     userId: 588,
  //     keyDisplayName: "A#min",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "AbMaj",
  //     mp3FileName: "Vodafone_Soniclogo_XOxNF0_2025-07-31T1246.mp3",
  //     matchingKeyId: "1",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "AbM",
  //     keyId: "1",
  //     id: 132,
  //     title: "Main",
  //     matchingKeyTuneyName: "AbM",
  //     userId: 588,
  //     keyDisplayName: "AbMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "AMaj",
  //     mp3FileName: "Vodafone_Soniclogo_vfNBrC_2025-07-31T1246.mp3",
  //     matchingKeyId: "2",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "AM",
  //     keyId: "2",
  //     id: 133,
  //     matchingKeyTuneyName: "AM",
  //     title: "Main",
  //     userId: 588,
  //     keyDisplayName: "AMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Amin",
  //     mp3FileName: "Vodafone_Soniclogo_1PB991_2025-07-31T1246.mp3",
  //     matchingKeyId: "18",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "Am",
  //     keyId: "18",
  //     id: 134,
  //     matchingKeyTuneyName: "Am",
  //     title: "Main",
  //     userId: 588,
  //     keyDisplayName: "Amin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "BbMaj",
  //     mp3FileName: "Vodafone_Soniclogo_3ZCG71_2025-07-31T1246.mp3",
  //     matchingKeyId: "3",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "BbM",
  //     keyId: "3",
  //     id: 135,
  //     matchingKeyTuneyName: "BbM",
  //     title: "Main",
  //     userId: 588,
  //     keyDisplayName: "BbMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "BMaj",
  //     mp3FileName: "Vodafone_Soniclogo_yznPVs_2025-07-31T1246.mp3",
  //     matchingKeyId: "4",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "BM",
  //     keyId: "4",
  //     id: 136,
  //     title: "Main",
  //     matchingKeyTuneyName: "BM",
  //     userId: 588,
  //     keyDisplayName: "BMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Bmin",
  //     mp3FileName: "Vodafone_Soniclogo_fKwWUa_2025-07-31T1246.mp3",
  //     matchingKeyId: "20",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "Bm",
  //     keyId: "20",
  //     id: 137,
  //     title: "Main",
  //     matchingKeyTuneyName: "Bm",
  //     userId: 588,
  //     keyDisplayName: "Bmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "C#Maj",
  //     mp3FileName: "Vodafone_Soniclogo_2bGtdO_2025-07-31T1246.mp3",
  //     matchingKeyId: "5",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "C#M",
  //     keyId: "5",
  //     id: 138,
  //     matchingKeyTuneyName: "C#M",
  //     title: "Main",
  //     userId: 588,
  //     keyDisplayName: "C#Maj",
  //   },
  //   {
  //     matchingKeyDisplayName: "C#min",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_Cshmb4_2025-07-31T1246.mp3",
  //     matchingKeyId: "21",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "C#m",
  //     keyId: "21",
  //     id: 139,
  //     matchingKeyTuneyName: "C#m",
  //     title: "Main",
  //     userId: 588,
  //     keyDisplayName: "C#min",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "CMaj",
  //     mp3FileName: "Vodafone_Soniclogo_g0lOmF_2025-07-31T1246.mp3",
  //     matchingKeyId: "6",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "CM",
  //     keyId: "6",
  //     id: 140,
  //     title: "Main",
  //     matchingKeyTuneyName: "CM",
  //     userId: 588,
  //     keyDisplayName: "CMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Cmin",
  //     mp3FileName: "Vodafone_Soniclogo_mBsQBe_2025-07-31T1246.mp3",
  //     matchingKeyId: "19",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyId: "19",
  //     keyTuneyName: "Cm",
  //     id: 141,
  //     title: "Main",
  //     matchingKeyTuneyName: "Cm",
  //     userId: 588,
  //     keyDisplayName: "Cmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "D#Maj",
  //     mp3FileName: "Vodafone_Soniclogo_D0bMfF_2025-07-31T1246.mp3",
  //     matchingKeyId: "7",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "D#M",
  //     keyId: "7",
  //     id: 142,
  //     title: "Main",
  //     matchingKeyTuneyName: "D#M",
  //     userId: 588,
  //     keyDisplayName: "D#Maj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "D#min",
  //     mp3FileName: "Vodafone_Soniclogo_NeiRIo_2025-07-31T1246.mp3",
  //     matchingKeyId: "22",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "D#m",
  //     keyId: "22",
  //     id: 143,
  //     title: "Main",
  //     matchingKeyTuneyName: "D#m",
  //     userId: 588,
  //     keyDisplayName: "D#min",
  //   },
  //   {
  //     matchingKeyDisplayName: "DMaj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_cQ2nlp_2025-07-31T1246.mp3",
  //     matchingKeyId: "8",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "DM",
  //     keyId: "8",
  //     id: 144,
  //     title: "Main",
  //     matchingKeyTuneyName: "DM",
  //     userId: 588,
  //     keyDisplayName: "DMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Dmin",
  //     mp3FileName: "Vodafone_Soniclogo_LnM2mo_2025-07-31T1246.mp3",
  //     matchingKeyId: "23",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "Dm",
  //     keyId: "23",
  //     id: 145,
  //     title: "Main",
  //     matchingKeyTuneyName: "Dm",
  //     userId: 588,
  //     keyDisplayName: "Dmin",
  //   },
  //   {
  //     matchingKeyDisplayName: "EMaj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_52jSgi_2025-07-31T1246.mp3",
  //     matchingKeyId: "9",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyId: "9",
  //     keyTuneyName: "EM",
  //     id: 146,
  //     title: "Main",
  //     matchingKeyTuneyName: "EM",
  //     userId: 588,
  //     keyDisplayName: "EMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Emin",
  //     mp3FileName: "Vodafone_Soniclogo_MSa8YP_2025-07-31T1246.mp3",
  //     matchingKeyId: "24",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "Em",
  //     keyId: "24",
  //     id: 147,
  //     title: "Main",
  //     matchingKeyTuneyName: "Em",
  //     userId: 588,
  //     keyDisplayName: "Emin",
  //   },
  //   {
  //     matchingKeyDisplayName: "F#Maj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_tk4Pjc_2025-07-31T1246.mp3",
  //     matchingKeyId: "10",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyId: "10",
  //     keyTuneyName: "F#M",
  //     id: 148,
  //     title: "Main",
  //     matchingKeyTuneyName: "F#M",
  //     userId: 588,
  //     keyDisplayName: "F#Maj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "F#min",
  //     mp3FileName: "Vodafone_Soniclogo_t4MsoT_2025-07-31T1246.mp3",
  //     matchingKeyId: "14",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "F#m",
  //     keyId: "14",
  //     id: 149,
  //     title: "Main",
  //     matchingKeyTuneyName: "F#m",
  //     userId: 588,
  //     keyDisplayName: "F#min",
  //   },
  //   {
  //     matchingKeyDisplayName: "FMaj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_w0qUm0_2025-07-31T1246.mp3",
  //     matchingKeyId: "11",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyId: "11",
  //     keyTuneyName: "FM",
  //     id: 150,
  //     title: "Main",
  //     matchingKeyTuneyName: "FM",
  //     userId: 588,
  //     keyDisplayName: "FMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Fmin",
  //     mp3FileName: "Vodafone_Soniclogo_zWrUA7_2025-07-31T1246.mp3",
  //     matchingKeyId: "13",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyId: "13",
  //     keyTuneyName: "Fm",
  //     id: 151,
  //     title: "Main",
  //     matchingKeyTuneyName: "Fm",
  //     userId: 588,
  //     keyDisplayName: "Fmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "G#min",
  //     mp3FileName: "Vodafone_Soniclogo_cscp3q_2025-07-31T1246.mp3",
  //     matchingKeyId: "16",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyTuneyName: "G#m",
  //     keyId: "16",
  //     id: 152,
  //     title: "Main",
  //     matchingKeyTuneyName: "G#m",
  //     userId: 588,
  //     keyDisplayName: "G#min",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "GMaj",
  //     mp3FileName: "Vodafone_Soniclogo_NvFJQo_2025-07-31T1246.mp3",
  //     matchingKeyId: "12",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyId: "12",
  //     keyTuneyName: "GM",
  //     id: 153,
  //     title: "Main",
  //     matchingKeyTuneyName: "GM",
  //     userId: 588,
  //     keyDisplayName: "GMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Gmin",
  //     mp3FileName: "Vodafone_Soniclogo_OYjHlL_2025-07-31T1246.mp3",
  //     matchingKeyId: "15",
  //     tuneyLogoId: "5e717e93-0ffa-40a5-a001-58d0ba557cf6",
  //     keyId: "15",
  //     keyTuneyName: "Gm",
  //     id: 154,
  //     title: "Main",
  //     matchingKeyTuneyName: "Gm",
  //     userId: 588,
  //     keyDisplayName: "Gmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "A#min",
  //     mp3FileName: "Vodafone_Soniclogo_XGkEFY_2025-07-31T130128.mp3",
  //     matchingKeyId: "17",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "A#m",
  //     keyId: "17",
  //     id: 155,
  //     matchingKeyTuneyName: "A#m",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "A#min",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "AbMaj",
  //     mp3FileName: "Vodafone_Soniclogo_h9ADR1_2025-07-31T130128.mp3",
  //     matchingKeyId: "1",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "AbM",
  //     keyId: "1",
  //     id: 156,
  //     matchingKeyTuneyName: "AbM",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "AbMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "AMaj",
  //     mp3FileName: "Vodafone_Soniclogo_bAMoJK_2025-07-31T130128.mp3",
  //     matchingKeyId: "2",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "AM",
  //     keyId: "2",
  //     id: 157,
  //     matchingKeyTuneyName: "AM",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "AMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Amin",
  //     mp3FileName: "Vodafone_Soniclogo_n9DCvp_2025-07-31T130128.mp3",
  //     matchingKeyId: "18",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "Am",
  //     keyId: "18",
  //     id: 158,
  //     matchingKeyTuneyName: "Am",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "Amin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "BbMaj",
  //     mp3FileName: "Vodafone_Soniclogo_C3SFEz_2025-07-31T130128.mp3",
  //     matchingKeyId: "3",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "BbM",
  //     keyId: "3",
  //     id: 159,
  //     matchingKeyTuneyName: "BbM",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "BbMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "BMaj",
  //     mp3FileName: "Vodafone_Soniclogo_FO4PpK_2025-07-31T130128.mp3",
  //     matchingKeyId: "4",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "BM",
  //     keyId: "4",
  //     id: 160,
  //     matchingKeyTuneyName: "BM",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "BMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Bmin",
  //     mp3FileName: "Vodafone_Soniclogo_bpypH8_2025-07-31T130128.mp3",
  //     matchingKeyId: "20",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "Bm",
  //     keyId: "20",
  //     id: 161,
  //     matchingKeyTuneyName: "Bm",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "Bmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "C#Maj",
  //     mp3FileName: "Vodafone_Soniclogo_fwAF96_2025-07-31T130128.mp3",
  //     matchingKeyId: "5",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "C#M",
  //     keyId: "5",
  //     id: 162,
  //     matchingKeyTuneyName: "C#M",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "C#Maj",
  //   },
  //   {
  //     matchingKeyDisplayName: "C#min",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_T7HhF5_2025-07-31T130128.mp3",
  //     matchingKeyId: "21",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "C#m",
  //     keyId: "21",
  //     id: 163,
  //     matchingKeyTuneyName: "C#m",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "C#min",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "CMaj",
  //     mp3FileName: "Vodafone_Soniclogo_DsQkSH_2025-07-31T130128.mp3",
  //     matchingKeyId: "6",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "CM",
  //     keyId: "6",
  //     id: 164,
  //     matchingKeyTuneyName: "CM",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "CMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Cmin",
  //     mp3FileName: "Vodafone_Soniclogo_1Wa2LP_2025-07-31T130128.mp3",
  //     matchingKeyId: "19",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyId: "19",
  //     keyTuneyName: "Cm",
  //     id: 165,
  //     matchingKeyTuneyName: "Cm",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "Cmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "D#Maj",
  //     mp3FileName: "Vodafone_Soniclogo_Y6xFkd_2025-07-31T130128.mp3",
  //     matchingKeyId: "7",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "D#M",
  //     keyId: "7",
  //     id: 166,
  //     matchingKeyTuneyName: "D#M",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "D#Maj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "D#min",
  //     mp3FileName: "Vodafone_Soniclogo_447ebK_2025-07-31T130128.mp3",
  //     matchingKeyId: "22",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "D#m",
  //     keyId: "22",
  //     id: 167,
  //     matchingKeyTuneyName: "D#m",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "D#min",
  //   },
  //   {
  //     matchingKeyDisplayName: "DMaj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_4wJQTz_2025-07-31T130128.mp3",
  //     matchingKeyId: "8",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "DM",
  //     keyId: "8",
  //     id: 168,
  //     matchingKeyTuneyName: "DM",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "DMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Dmin",
  //     mp3FileName: "Vodafone_Soniclogo_EL005Y_2025-07-31T130128.mp3",
  //     matchingKeyId: "23",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "Dm",
  //     keyId: "23",
  //     id: 169,
  //     matchingKeyTuneyName: "Dm",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "Dmin",
  //   },
  //   {
  //     matchingKeyDisplayName: "EMaj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_WtE8rs_2025-07-31T130128.mp3",
  //     matchingKeyId: "9",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyId: "9",
  //     keyTuneyName: "EM",
  //     id: 170,
  //     matchingKeyTuneyName: "EM",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "EMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Emin",
  //     mp3FileName: "Vodafone_Soniclogo_mtlbU3_2025-07-31T130128.mp3",
  //     matchingKeyId: "24",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "Em",
  //     keyId: "24",
  //     id: 171,
  //     matchingKeyTuneyName: "Em",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "Emin",
  //   },
  //   {
  //     matchingKeyDisplayName: "F#Maj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_G4lQL5_2025-07-31T130128.mp3",
  //     matchingKeyId: "10",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyId: "10",
  //     keyTuneyName: "F#M",
  //     id: 172,
  //     matchingKeyTuneyName: "F#M",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "F#Maj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "F#min",
  //     mp3FileName: "Vodafone_Soniclogo_nQMNlq_2025-07-31T130128.mp3",
  //     matchingKeyId: "14",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "F#m",
  //     keyId: "14",
  //     id: 173,
  //     matchingKeyTuneyName: "F#m",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "F#min",
  //   },
  //   {
  //     matchingKeyDisplayName: "FMaj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_zHmRKl_2025-07-31T130128.mp3",
  //     matchingKeyId: "11",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyId: "11",
  //     keyTuneyName: "FM",
  //     id: 174,
  //     matchingKeyTuneyName: "FM",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "FMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Fmin",
  //     mp3FileName: "Vodafone_Soniclogo_v1MkgR_2025-07-31T130128.mp3",
  //     matchingKeyId: "13",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyId: "13",
  //     keyTuneyName: "Fm",
  //     id: 175,
  //     matchingKeyTuneyName: "Fm",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "Fmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "G#min",
  //     mp3FileName: "Vodafone_Soniclogo_aNrNOa_2025-07-31T130128.mp3",
  //     matchingKeyId: "16",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyTuneyName: "G#m",
  //     keyId: "16",
  //     id: 176,
  //     matchingKeyTuneyName: "G#m",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "G#min",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "GMaj",
  //     mp3FileName: "Vodafone_Soniclogo_GrVUD7_2025-07-31T130128.mp3",
  //     matchingKeyId: "12",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyId: "12",
  //     keyTuneyName: "GM",
  //     id: 177,
  //     matchingKeyTuneyName: "GM",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "GMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Gmin",
  //     mp3FileName: "Vodafone_Soniclogo_XlhW68_2025-07-31T130128.mp3",
  //     matchingKeyId: "15",
  //     tuneyLogoId: "699df919-e5bb-4925-aa63-87022a3b3853",
  //     keyId: "15",
  //     keyTuneyName: "Gm",
  //     id: 178,
  //     matchingKeyTuneyName: "Gm",
  //     title: "Arabic",
  //     userId: 588,
  //     keyDisplayName: "Gmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "AbMaj",
  //     mp3FileName: "Vodafone_Soniclogo_KSDufS_2025-07-31T130745.mp3",
  //     matchingKeyId: "1",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "AbM",
  //     keyId: "1",
  //     id: 179,
  //     matchingKeyTuneyName: "AbM",
  //     title: "Electronic",
  //     userId: 588,
  //     keyDisplayName: "AbMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "AMaj",
  //     mp3FileName: "Vodafone_Soniclogo_nwDXIB_2025-07-31T130745.mp3",
  //     matchingKeyId: "2",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "AM",
  //     keyId: "2",
  //     id: 180,
  //     matchingKeyTuneyName: "AM",
  //     title: "Electronic",
  //     userId: 588,
  //     keyDisplayName: "AMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Amin",
  //     mp3FileName: "Vodafone_Soniclogo_kIqqun_2025-07-31T130745.mp3",
  //     matchingKeyId: "18",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "Am",
  //     keyId: "18",
  //     id: 181,
  //     matchingKeyTuneyName: "Am",
  //     title: "Electronic",
  //     userId: 588,
  //     keyDisplayName: "Amin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "BbMaj",
  //     mp3FileName: "Vodafone_Soniclogo_4pCxwY_2025-07-31T130745.mp3",
  //     matchingKeyId: "3",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "BbM",
  //     keyId: "3",
  //     id: 182,
  //     matchingKeyTuneyName: "BbM",
  //     title: "Electronic",
  //     userId: 588,
  //     keyDisplayName: "BbMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "BMaj",
  //     mp3FileName: "Vodafone_Soniclogo_E0oKNa_2025-07-31T130745.mp3",
  //     matchingKeyId: "4",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "BM",
  //     keyId: "4",
  //     id: 183,
  //     title: "Electronic",
  //     matchingKeyTuneyName: "BM",
  //     userId: 588,
  //     keyDisplayName: "BMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Bmin",
  //     mp3FileName: "Vodafone_Soniclogo_oaIxN0_2025-07-31T130745.mp3",
  //     matchingKeyId: "20",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "Bm",
  //     keyId: "20",
  //     id: 184,
  //     title: "Electronic",
  //     matchingKeyTuneyName: "Bm",
  //     userId: 588,
  //     keyDisplayName: "Bmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "C#Maj",
  //     mp3FileName: "Vodafone_Soniclogo_Ld6uap_2025-07-31T130745.mp3",
  //     matchingKeyId: "5",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "C#M",
  //     keyId: "5",
  //     id: 185,
  //     matchingKeyTuneyName: "C#M",
  //     title: "Electronic",
  //     userId: 588,
  //     keyDisplayName: "C#Maj",
  //   },
  //   {
  //     matchingKeyDisplayName: "C#min",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_IMfCz2_2025-07-31T130745.mp3",
  //     matchingKeyId: "21",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "C#m",
  //     keyId: "21",
  //     id: 186,
  //     matchingKeyTuneyName: "C#m",
  //     title: "Electronic",
  //     userId: 588,
  //     keyDisplayName: "C#min",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "CMaj",
  //     mp3FileName: "Vodafone_Soniclogo_tjt17Z_2025-07-31T130745.mp3",
  //     matchingKeyId: "6",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "CM",
  //     keyId: "6",
  //     id: 187,
  //     title: "Electronic",
  //     matchingKeyTuneyName: "CM",
  //     userId: 588,
  //     keyDisplayName: "CMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Cmin",
  //     mp3FileName: "Vodafone_Soniclogo_nQoMXG_2025-07-31T130745.mp3",
  //     matchingKeyId: "19",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyId: "19",
  //     keyTuneyName: "Cm",
  //     id: 188,
  //     title: "Electronic",
  //     matchingKeyTuneyName: "Cm",
  //     userId: 588,
  //     keyDisplayName: "Cmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "D#Maj",
  //     mp3FileName: "Vodafone_Soniclogo_r6z8wY_2025-07-31T130745.mp3",
  //     matchingKeyId: "7",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "D#M",
  //     keyId: "7",
  //     id: 189,
  //     matchingKeyTuneyName: "D#M",
  //     title: "Electronic",
  //     userId: 588,
  //     keyDisplayName: "D#Maj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "D#min",
  //     mp3FileName: "Vodafone_Soniclogo_sKt3S0_2025-07-31T130745.mp3",
  //     matchingKeyId: "22",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "D#m",
  //     keyId: "22",
  //     id: 190,
  //     matchingKeyTuneyName: "D#m",
  //     title: "Electronic",
  //     userId: 588,
  //     keyDisplayName: "D#min",
  //   },
  //   {
  //     matchingKeyDisplayName: "DMaj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_97cXSX_2025-07-31T130745.mp3",
  //     matchingKeyId: "8",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "DM",
  //     keyId: "8",
  //     id: 191,
  //     matchingKeyTuneyName: "DM",
  //     title: "Electronic",
  //     userId: 588,
  //     keyDisplayName: "DMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Dmin",
  //     mp3FileName: "Vodafone_Soniclogo_NskSBe_2025-07-31T130745.mp3",
  //     matchingKeyId: "23",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "Dm",
  //     keyId: "23",
  //     id: 192,
  //     matchingKeyTuneyName: "Dm",
  //     title: "Electronic",
  //     userId: 588,
  //     keyDisplayName: "Dmin",
  //   },
  //   {
  //     matchingKeyDisplayName: "EMaj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_oxII4I_2025-07-31T130745.mp3",
  //     matchingKeyId: "9",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyId: "9",
  //     keyTuneyName: "EM",
  //     id: 193,
  //     matchingKeyTuneyName: "EM",
  //     title: "Electronic",
  //     userId: 588,
  //     keyDisplayName: "EMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Emin",
  //     mp3FileName: "Vodafone_Soniclogo_8ut2aB_2025-07-31T130745.mp3",
  //     matchingKeyId: "24",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "Em",
  //     keyId: "24",
  //     id: 194,
  //     matchingKeyTuneyName: "Em",
  //     title: "Electronic",
  //     userId: 588,
  //     keyDisplayName: "Emin",
  //   },
  //   {
  //     matchingKeyDisplayName: "F#Maj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_2Is5s2_2025-07-31T130745.mp3",
  //     matchingKeyId: "10",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyId: "10",
  //     keyTuneyName: "F#M",
  //     id: 195,
  //     title: "Electronic",
  //     matchingKeyTuneyName: "F#M",
  //     userId: 588,
  //     keyDisplayName: "F#Maj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "F#min",
  //     mp3FileName: "Vodafone_Soniclogo_vWHh0l_2025-07-31T130745.mp3",
  //     matchingKeyId: "14",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "F#m",
  //     keyId: "14",
  //     id: 196,
  //     title: "Electronic",
  //     matchingKeyTuneyName: "F#m",
  //     userId: 588,
  //     keyDisplayName: "F#min",
  //   },
  //   {
  //     matchingKeyDisplayName: "FMaj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_kLGHXm_2025-07-31T130745.mp3",
  //     matchingKeyId: "11",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyId: "11",
  //     keyTuneyName: "FM",
  //     id: 197,
  //     title: "Electronic",
  //     matchingKeyTuneyName: "FM",
  //     userId: 588,
  //     keyDisplayName: "FMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Fmin",
  //     mp3FileName: "Vodafone_Soniclogo_9G6dOv_2025-07-31T130745.mp3",
  //     matchingKeyId: "13",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyId: "13",
  //     keyTuneyName: "Fm",
  //     id: 198,
  //     title: "Electronic",
  //     matchingKeyTuneyName: "Fm",
  //     userId: 588,
  //     keyDisplayName: "Fmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "G#min",
  //     mp3FileName: "Vodafone_Soniclogo_RnNWuM_2025-07-31T130745.mp3",
  //     matchingKeyId: "16",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyTuneyName: "G#m",
  //     keyId: "16",
  //     id: 199,
  //     title: "Electronic",
  //     matchingKeyTuneyName: "G#m",
  //     userId: 588,
  //     keyDisplayName: "G#min",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "GMaj",
  //     mp3FileName: "Vodafone_Soniclogo_108G7B_2025-07-31T130745.mp3",
  //     matchingKeyId: "12",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyId: "12",
  //     keyTuneyName: "GM",
  //     id: 200,
  //     title: "Electronic",
  //     matchingKeyTuneyName: "GM",
  //     userId: 588,
  //     keyDisplayName: "GMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Gmin",
  //     mp3FileName: "Vodafone_Soniclogo_nlVK1m_2025-07-31T130745.mp3",
  //     matchingKeyId: "15",
  //     tuneyLogoId: "b8c58526-89c6-46b4-8025-c05cb70912cc",
  //     keyId: "15",
  //     keyTuneyName: "Gm",
  //     id: 201,
  //     title: "Electronic",
  //     matchingKeyTuneyName: "Gm",
  //     userId: 588,
  //     keyDisplayName: "Gmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "AbMaj",
  //     mp3FileName: "Vodafone_Soniclogo_1iTLLV_2025-07-31T132403.mp3",
  //     matchingKeyId: "1",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "AbM",
  //     keyId: "1",
  //     id: 202,
  //     matchingKeyTuneyName: "AbM",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "AbMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "AMaj",
  //     mp3FileName: "Vodafone_Soniclogo_HPLuVp_2025-07-31T132403.mp3",
  //     matchingKeyId: "2",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "AM",
  //     keyId: "2",
  //     id: 203,
  //     matchingKeyTuneyName: "AM",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "AMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Amin",
  //     mp3FileName: "Vodafone_Soniclogo_I4cpJn_2025-07-31T132403.mp3",
  //     matchingKeyId: "18",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "Am",
  //     keyId: "18",
  //     id: 204,
  //     matchingKeyTuneyName: "Am",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "Amin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "BbMaj",
  //     mp3FileName: "Vodafone_Soniclogo_zF7wOC_2025-07-31T132403.mp3",
  //     matchingKeyId: "3",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "BbM",
  //     keyId: "3",
  //     id: 205,
  //     matchingKeyTuneyName: "BbM",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "BbMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "BMaj",
  //     mp3FileName: "Vodafone_Soniclogo_1m73NN_2025-07-31T132403.mp3",
  //     matchingKeyId: "4",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "BM",
  //     keyId: "4",
  //     id: 206,
  //     matchingKeyTuneyName: "BM",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "BMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Bmin",
  //     mp3FileName: "Vodafone_Soniclogo_EsQiBq_2025-07-31T132403.mp3",
  //     matchingKeyId: "20",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "Bm",
  //     keyId: "20",
  //     id: 207,
  //     matchingKeyTuneyName: "Bm",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "Bmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "C#Maj",
  //     mp3FileName: "Vodafone_Soniclogo_9lcrOL_2025-07-31T132403.mp3",
  //     matchingKeyId: "5",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "C#M",
  //     keyId: "5",
  //     id: 208,
  //     matchingKeyTuneyName: "C#M",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "C#Maj",
  //   },
  //   {
  //     matchingKeyDisplayName: "C#min",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_c4E32F_2025-07-31T132403.mp3",
  //     matchingKeyId: "21",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "C#m",
  //     keyId: "21",
  //     id: 209,
  //     matchingKeyTuneyName: "C#m",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "C#min",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "CMaj",
  //     mp3FileName: "Vodafone_Soniclogo_91Ymtt_2025-07-31T132403.mp3",
  //     matchingKeyId: "6",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "CM",
  //     keyId: "6",
  //     id: 210,
  //     matchingKeyTuneyName: "CM",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "CMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Cmin",
  //     mp3FileName: "Vodafone_Soniclogo_htcXZ8_2025-07-31T132404.mp3",
  //     matchingKeyId: "19",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyId: "19",
  //     keyTuneyName: "Cm",
  //     id: 211,
  //     matchingKeyTuneyName: "Cm",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "Cmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "D#Maj",
  //     mp3FileName: "Vodafone_Soniclogo_Uz4AvH_2025-07-31T132403.mp3",
  //     matchingKeyId: "7",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "D#M",
  //     keyId: "7",
  //     id: 212,
  //     matchingKeyTuneyName: "D#M",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "D#Maj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "D#min",
  //     mp3FileName: "Vodafone_Soniclogo_9Tbu8y_2025-07-31T132403.mp3",
  //     matchingKeyId: "22",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "D#m",
  //     keyId: "22",
  //     id: 213,
  //     matchingKeyTuneyName: "D#m",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "D#min",
  //   },
  //   {
  //     matchingKeyDisplayName: "DMaj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_753DzU_2025-07-31T132403.mp3",
  //     matchingKeyId: "8",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "DM",
  //     keyId: "8",
  //     id: 214,
  //     matchingKeyTuneyName: "DM",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "DMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Dmin",
  //     mp3FileName: "Vodafone_Soniclogo_ORGln9_2025-07-31T132403.mp3",
  //     matchingKeyId: "23",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "Dm",
  //     keyId: "23",
  //     id: 215,
  //     matchingKeyTuneyName: "Dm",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "Dmin",
  //   },
  //   {
  //     matchingKeyDisplayName: "EMaj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_pywALR_2025-07-31T132403.mp3",
  //     matchingKeyId: "9",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyId: "9",
  //     keyTuneyName: "EM",
  //     id: 216,
  //     matchingKeyTuneyName: "EM",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "EMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Emin",
  //     mp3FileName: "Vodafone_Soniclogo_jyADEf_2025-07-31T132403.mp3",
  //     matchingKeyId: "24",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "Em",
  //     keyId: "24",
  //     id: 217,
  //     matchingKeyTuneyName: "Em",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "Emin",
  //   },
  //   {
  //     matchingKeyDisplayName: "F#Maj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_ZopJpf_2025-07-31T132403.mp3",
  //     matchingKeyId: "10",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyId: "10",
  //     keyTuneyName: "F#M",
  //     id: 218,
  //     title: "Guitar",
  //     matchingKeyTuneyName: "F#M",
  //     userId: 588,
  //     keyDisplayName: "F#Maj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "F#min",
  //     mp3FileName: "Vodafone_Soniclogo_8rz8Te_2025-07-31T132403.mp3",
  //     matchingKeyId: "14",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "F#m",
  //     keyId: "14",
  //     id: 219,
  //     title: "Guitar",
  //     matchingKeyTuneyName: "F#m",
  //     userId: 588,
  //     keyDisplayName: "F#min",
  //   },
  //   {
  //     matchingKeyDisplayName: "FMaj",
  //     duration: 3,
  //     mp3FileName: "Vodafone_Soniclogo_os94zI_2025-07-31T132403.mp3",
  //     matchingKeyId: "11",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyId: "11",
  //     keyTuneyName: "FM",
  //     id: 220,
  //     matchingKeyTuneyName: "FM",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "FMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Fmin",
  //     mp3FileName: "Vodafone_Soniclogo_D7Kers_2025-07-31T132403.mp3",
  //     matchingKeyId: "13",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyId: "13",
  //     keyTuneyName: "Fm",
  //     id: 221,
  //     matchingKeyTuneyName: "Fm",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "Fmin",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "G#min",
  //     mp3FileName: "Vodafone_Soniclogo_YmZCni_2025-07-31T132403.mp3",
  //     matchingKeyId: "16",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyTuneyName: "G#m",
  //     keyId: "16",
  //     id: 222,
  //     title: "Guitar",
  //     matchingKeyTuneyName: "G#m",
  //     userId: 588,
  //     keyDisplayName: "G#min",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "GMaj",
  //     mp3FileName: "Vodafone_Soniclogo_UJrshw_2025-07-31T132403.mp3",
  //     matchingKeyId: "12",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyId: "12",
  //     keyTuneyName: "GM",
  //     id: 223,
  //     matchingKeyTuneyName: "GM",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "GMaj",
  //   },
  //   {
  //     duration: 3,
  //     matchingKeyDisplayName: "Gmin",
  //     mp3FileName: "Vodafone_Soniclogo_4pzfj8_2025-07-31T132403.mp3",
  //     matchingKeyId: "15",
  //     tuneyLogoId: "187883fb-a328-44b9-a0da-eea8c3cd941a",
  //     keyId: "15",
  //     keyTuneyName: "Gm",
  //     id: 224,
  //     matchingKeyTuneyName: "Gm",
  //     title: "Guitar",
  //     userId: 588,
  //     keyDisplayName: "Gmin",
  //   },
  // ];
};

const SonicLogoPanel = () => {
  const [isSonicLogoModalOpen, setIsSonicLogoModalOpen] = useState(false);
  const [sonicLogoMeta, setSonicLogoMeta] = useState(0);
  const { selectedAIMusicDetails, endingOption, sonicLogoId } = useSelector(
    (state) => state.AIMusic
  );
  const { allSonicLogoTracks, sonicLogoRecommendedTracks, isFetched } =
    useSelector((state) => state.sonicLogoTrack);
  const dispatch = useDispatch();

  let AITrackMatchingKey = selectedAIMusicDetails?.settings?.key;
  useEffect(() => {
    if (!AITrackMatchingKey) return;
    getSonicLogoTracks(isFetched, AITrackMatchingKey);
  }, [AITrackMatchingKey]);

  const getSonicLogoTracks = async (isFetched, AITrackMatchingKey) => {
    try {
      let allSonicLogoTracksArr;
      if (allSonicLogoTracks?.length === 0 && !isFetched) {
        try {
          allSonicLogoTracksArr = await getAllSonicLogoTracks();
          dispatch(
            SET_SONIC_LOGO_TRACK_META({
              allSonicLogoTracks: allSonicLogoTracksArr,
              isFetched: true,
            })
          );
        } catch (error) {
          allSonicLogoTracksArr = [];
        }
      } else {
        allSonicLogoTracksArr = allSonicLogoTracks;
      }
      // console.log("allSonicLogoTracksArr", allSonicLogoTracksArr);
      // console.log("AI music key :: ", AITrackMatchingKey);
      let recommandedSonicLogosArr = filter(
        allSonicLogoTracksArr ?? [],
        (track) => track.matchingKeyTuneyName === AITrackMatchingKey
      );
      // let recommandedSonicLogosArr = allSonicLogoTracksArr;
      // console.log(
      //   "recommandedSonicLogosArr",
      //   JSON.stringify(recommandedSonicLogosArr, null, 2)
      // );

      dispatch(
        SET_SONIC_LOGO_TRACK_META({
          sonicLogoRecommendedTracks: recommandedSonicLogosArr,
        })
      );
    } catch (error) {
      console.log("getSonicLogoTracks error :: ", error);
      dispatch(
        SET_SONIC_LOGO_TRACK_META({
          allSonicLogoTracks: [],
          sonicLogoRecommendedTracks: [],
          isFetched: true,
        })
      );
    }
  };

  const showHideSonicLogoPanel = (endingOption, element) => {
    if (endingOption === "add_sonic_logo") {
      element.style.maxHeight = element.scrollHeight + 15 + "px";
      element.style.marginBottom = "15px";
    } else {
      dispatch(
        SET_AI_MUSIC_META({
          playedSonicLogo: null,
        })
      );
      element.style.maxHeight = null;
      element.style.marginBottom = "0px";
    }
  };

  const sonicLogoPanelRef = useRef(null);

  useEffect(() => {
    if (!sonicLogoPanelRef.current?.id) return;
    showHideSonicLogoPanel(endingOption, sonicLogoPanelRef.current);
  }, [
    endingOption,
    sonicLogoPanelRef.current?.id,
    sonicLogoPanelRef.current?.scrollHeight,
  ]);

  const { audioCommonRef, playingAudio, setPlayingAudio, playPause } =
    useSonicLogoTrackPlayPause();

  if (sonicLogoRecommendedTracks?.length === 0) {
    return <></>;
  }

  return (
    <div
      className={`sonic_logo_panel`}
      id={`sonic_logo_panel`}
      ref={sonicLogoPanelRef}
      key={selectedAIMusicDetails?.settings?.key}
    >
      <audio
        id="sonic_logo_audio"
        onError={() => {
          showNotification("ERROR", "Something went wrong!");
          setPlayingAudio((prev) => ({
            ...prev,
            isLoading: false,
          }));
        }}
        controlsList="nodownload noplaybackrate"
        ref={audioCommonRef}
        controls
        onEnded={() => {
          setPlayingAudio((prev) => ({
            ...prev,
            isPlaying: false,
          }));
        }}
        onPlay={() => {
          setPlayingAudio((prev) => ({
            ...prev,
            isPlaying: true,
            isLoading: false,
          }));
        }}
        onPause={() => {
          setPlayingAudio((prev) => ({
            ...prev,
            isPlaying: false,
          }));
        }}
      />
      {sonicLogoRecommendedTracks?.length > 0 && isFetched && (
        <section className="recommended_sonic_logo_container sonic_logo_panel_item">
          <ModalWrapper
            isOpen={isSonicLogoModalOpen}
            onClose={() => setIsSonicLogoModalOpen(false)}
            title={""}
            className="sonic_logo_append"
          >
            <AppendSonicLogo
              setIsSonicLogoModalOpen={setIsSonicLogoModalOpen}
              sonicLogoMeta={sonicLogoMeta}
            />
          </ModalWrapper>
          <p className="sonic_logo_panel_title boldFamily">{`Recommended Sonic Logo${
            sonicLogoRecommendedTracks?.length > 1 ? "s" : ""
          }`}</p>
          <div className="sonic_logo_panel_item_container">
            {sonicLogoRecommendedTracks?.map((item, i) => (
              <SonicLogoItem
                key={selectedAIMusicDetails?.cue_id + item?.tuneyLogoId + i}
                data={item}
                playingAudio={playingAudio}
                playPause={playPause}
                setPlayingAudio={setPlayingAudio}
                audioCommonRef={audioCommonRef}
                setIsSonicLogoModalOpen={setIsSonicLogoModalOpen}
                setSonicLogoMeta={setSonicLogoMeta}
              />
            ))}
          </div>
        </section>
      )}
    </div>
  );
};

export default SonicLogoPanel;
