export const AIMusicActions = {
  SONIC_LOGO_APPEND: "SONIC_LOGO_APPEND",
  VARIANT: "VARIANT",
  APPLIED_CHANGES: "APPLIED_CHANGES",
  LENGTH_CHANGE: "LENGTH_CHANGE",
  REMIX_INSTRUMENT: "REMIX_INSTRUMENT",
  MUTE_INSTRUMENT: "MUTE_INSTRUMENT",
  FLAX_TRACK: "FLAX_TRACK",
  ADD_DROP: "ADD_DROP",
  ADD_ENDING: "ADD_ENDING",
  ADD_DROP_AND_ENDING: "ADD_DROP_AND_ENDING",
  ADD_DROP_AND_INSTRUMENT_UPDATE: "ADD_DROP_AND_INSTRUMENT_UPDATE",
  INSTRUMENT_UPDATE: "INSTRUMENT_UPDATE",
};
